name: CI - Tests & Rapport

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Java 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8.0.392+8
          cache: maven

      - name: Build & installer les modules
        run: mvn --file src/pom.xml clean install --batch-mode

      - name: Générer site (rapport de tests)
        run: mvn --file src/pom.xml site --batch-mode

      - name: Publier le rapport de tests
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: src/*/target/site/surefire-report.html